version: '4'

services:
  project:
    image: python:3.11.6
    #restart: always
    ports:
      - '5623:5623'
    volumes:
      - ../get_user_url:/var/project/get_user_url
    command: >
            bash -c "set -x &&
            cd /var/project/get_user_url  &&
            python -m venv venv &&
            source venv/bin/activate &&
            pip install poetry &&
            poetry install --no-root &&
            poetry update &&
            python src/main.py"

    working_dir: /var/project/get_user_url
    environment:
      - URL=https://randomuser.me/api/?results=
      - USER_KAFKA=aGFybWxlc3MtbGxhbWEtMTA5NTUkSWlsftAT5bb2G5AxTAXsG48EcNi8Pk20sDU
      - PASSWORD_KAFKA=YzI5N2JhYzQtZGJjMi00YjJmLThjOTQtMTEwNzhiZjQ3MmNm
      - TOPIC=test_msg
      - PYTHONPATH=/var/project/get_user_url
